# Generated by Django 4.0.6 on 2022-07-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_racing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racing',
            name='location',
            field=models.TextField(default='123 South Street, Endicot NY 11219', max_length=100),
        ),
    ]
