# Generated by Django 4.0.6 on 2022-07-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_racing_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racing',
            options={'ordering': ['-date']},
        ),
    ]
